### ISSUE TITLE
Turn off the default control lasso button

### ISSUE THREAD

**Issue by nevrome** [zakjan/leaflet-lasso#12]
This package works great! Thank you!

Is there an option to turn off the default control lasso button in the top right corner to replace it entirely with a custom button?

**Comment by zakjan** [comment]
Thanks!

Sure there is such option, it was actually v1 implementation without the button yet. Don't use `L.control.lasso`, but `L.lasso` directly, and you can activate it on clicking any custom button.

https://github.com/zakjan/leaflet-lasso#handler

**Comment by nevrome** [comment]
Ah - excellent. That works. Thanks again!
