### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by MicahStevens** [zakjan/leaflet-lasso#20]
I need to integrate touch support for this tool, I have some ideas but as I'm new to plugin dev for leaflet I was wondering if you had particular recommendations on how to accomplish this? Just merely adding touch events to the existing handlers doesn't work, so I'll have to dig in more.

**Comment by zakjan** [comment]
The issue is likely in https://github.com/zakjan/leaflet-lasso/blob/master/src/lasso-handler.ts#L120-L125, this code is applicable only in mouse scenario. Then I suppose adding touch events should work.

**Comment by MicahStevens** [comment]
Thank you, I'll open a pull request in case you want to include it in the main repo once I get it working. Appreciate the input.

**Comment by zakjan** [comment]
Awesome, I'm looking forward to it, thanks! :)

**Comment by niharsalunke** [comment]
Is the touch support enabled? I have had a great help with your code, but I am looking forward to extend its compatibilities with touch screen devices. Please Help.

**Comment by MicahStevens** [comment]
I started working on a patch for touch support, but it's not complete. I'll post here and submit a pull request when I get something working, but I had to set it aside for a little while due to other priorities.

**Comment by niharsalunke** [comment]
> 
> 
> I started working on a patch for touch support, but it's not complete. I'll post here and submit a pull request when I get something working, but I had to set it aside for a little while due to other priorities.

Thank You so much for the reply. The feature is much awaited. 😄😄

**Comment by zakjan** [comment]
Hi @MicahStevens @niharsalunke, I released touch support as 2.2.0, could you take a look if it works well for you?

**Comment by MicahStevens** [comment]
Great! Thank you, much appreciated, I didn't think to use the map container. I can try out today on android tablet + phone and iOS tablet + phone, plus an embedded touchscreen chrome device.
