### ISSUE TITLE
Error with usage in Angular/Typescript

### ISSUE THREAD

**Issue by JanLoebel** [zakjan/leaflet-lasso#21]
Hi there,

first of all, thank you so much for you're great leaflet plugin. I'm using it in Angular with Typescript and with 2.0.8 i get the following error:

```
ERROR in node_modules/leaflet-lasso/dist/lasso-control.d.ts(1,8): error TS1192: Module '"node_modules/@types/leaflet/index"' has no default export.
    node_modules/leaflet-lasso/dist/lasso-handler.d.ts(1,8): error TS1192: Module '"node_modules/@types/leaflet/index"' has no default export.
    node_modules/leaflet-lasso/dist/lasso-polygon.d.ts(1,8): error TS1192: Module '"node_modules/@types/leaflet/index"' has no default export.
```

as far as I know you have to write the import for leaflet like this:

`import * as L from 'leaflet';`

because leaflet (even with version 1.6.0) does not have a default export in their module configuration. Could you check that?

Best regards,
Jan

**Comment by zakjan** [comment]
Right, it works only with enabled esModuleInterop in tsconfig, I should probably reset it here to the default state to support all kinds of downstream projects

**Comment by zakjan** [comment]
So I tried it, but then TS doesn't allow me to assign to L.lasso, because it is readonly. Can you enable esModuleInterop in your project? Otherwise I'd need to either stop assigning to L.lasso and support only proper named exports, or produce two separate bundles.

**Comment by JanLoebel** [comment]
Sorry, I'm not able to enable "esModuleInterop" sorry.

**Comment by zakjan** [comment]
Do you use other Leaflet plugins?

**Comment by JanLoebel** [comment]
Yes, I'm using:
- leaflet.markercluster  (with: @types/leaflet.markercluster)
- @geoman-io/leaflet-geoman-free (not typed)
- leaflet.fullscreen (not typed)

**Comment by zakjan** [comment]
@JanLoebel Hi, would you mind trying out the new released 2.1.0? I disabled `esModuleInterop` and switched to bundling d.ts with `rollup-plugin-dts`.

**Comment by JanLoebel** [comment]
@zakjan I will give it a try this week and let you know :) Thanks!

**Comment by JanLoebel** [comment]
@zakjan looks great! Thank you so much :)
