### ISSUE TITLE
Problem with Angular and IE11

### ISSUE THREAD

**Issue by JanLoebel** [zakjan/leaflet-lasso#23]
Hi, 

we had a problem with a missing semicolon in your dependencies:

https://github.com/gabzim/circle-to-polygon

I've already done a pull-request with was merged and a new release was done with version: 2.0.2. Could you please update that dependency so we could use leaflet-lasso with IE11 and Angular?! :)

Best regards,
Jan

**Comment by zakjan** [comment]
Awesome, released in 2.0.9, thanks a lot!

**Comment by JanLoebel** [comment]
Thanks I will give it a try :)
