### ISSUE TITLE
lasso.finished performance for large geojson feature set

### ISSUE THREAD

**Issue by erodrig9** [zakjan/leaflet-lasso#24]
I am working on a prototype to select from zip/postal code features.  Currently I am only loading the data for one state.  After the lasso selection is done, even for a small selection, there is about a 10s lag until the lasso.finished event is fired.

Attached example.
[example.zip](https://github.com/zakjan/leaflet-lasso/files/4927782/example.zip)

**Comment by zakjan** [comment]
Hi @erodrig9, until I can investigate possible improvements, is it feasible for you to turn off intersect mode? Default contain mode is significantly faster in your example. ~1s instead of a few secs.

**Comment by erodrig9** [comment]
Hi @zakjan, the preferred behavior would be intersection but I will check if we can get by with contain for now.  Thanks for looking into this.

**Comment by niharsalunke** [comment]
As a part of an NGO project, I have used your lasso feature in my project. you may find the implementation at https://bloomindia.in/search-donor . I hope your efforts will help someone. 😄❤ The project is still in beta phase and depends on a Google API which gets exhausted during testing.

**Comment by zakjan** [comment]
@niharsalunke Glad it helped you! I was recently accepted for GitHub Sponsors https://github.com/sponsors/zakjan so if anyone benefits from my open-source activities, now there is a way to sponsor them.

**Comment by zakjan** [comment]
@erodrig9 I have published 2.1.2, which contains two performance improvements for your case, see the [changelog](https://github.com/zakjan/leaflet-lasso/blob/master/CHANGELOG.md). It got better when doing a small selection. Could you try it?

The slowness is still noticeable when doing a large selection around all the polygons. For further improvements, I should probably use a specialized index data structure.

**Comment by erodrig9** [comment]
@zakjan  Thanks!  I will try it out.

**Comment by erodrig9** [comment]
@zakjan This is working significantly faster.  Appreciate the effort.

**Comment by zakjan** [comment]
Thanks! Closing.
