### ISSUE TITLE
performance for too many layers

### ISSUE THREAD

**Issue by SixiCat** [zakjan/leaflet-lasso#28]
hi!
there is  a project that has too many layers,  leaflet-lasso needs 10~20s until the lasso selection is done. 
so,  is there a option that make lasso just pick selected layer in the given layers，instead of the map's all layers.

thanks!!!

**Comment by zakjan** [comment]
Hi @SixiCat, performance was improved in #24, have you tried the latest release? There is no such option yet, it checks all layers. Do you activate lasso by the provided control or handler? What do you mean by "selected layer", could you post an example?

**Comment by SixiCat** [comment]
sorry, it's my fault.  The "selected layer" is point this 
![image](https://user-images.githubusercontent.com/10220442/91113857-1abaa800-e6b9-11ea-91a2-a9573ffd2132.png)
[source code]( https://github.com/zakjan/leaflet-lasso/blob/c87d577d80b30a7e9aa88385eb80cc6ab7731063/src/calc.ts#L58).

If there is an option that can set the layers before activate lasso, we don't need to waste time on irrelevant layers.
![image](https://user-images.githubusercontent.com/10220442/91114635-f3fd7100-e6ba-11ea-9e6e-1fb3133eafb2.png)

**Comment by zakjan** [comment]
Would adding a filter function option work for your use case?

```
export interface LassoHandlerOptions {
    polygon?: L.PolylineOptions,
    intersect?: boolean;
    filter?: (layer: L.Layer) => boolean;
}
```

**Comment by SixiCat** [comment]
thanks for your work.
I also think it will help for my project.
