### ISSUE TITLE
Any chance you could make this work with Leaflet.SvgShapeMarkers?

### ISSUE THREAD

**Issue by gemmavnash** [zakjan/leaflet-lasso#29]
This library works great with normal leaflet circleMarkers, but I need to have different shaped markers on my map so am using https://github.com/rowanwins/Leaflet.SvgShapeMarkers 
I get this error on lasso.finished:
t-spatial.esm.js:522 
Uncaught TypeError: Cannot read property 'type' of undefined
    at t (t-spatial.esm.js:522)
    at calc.ts:6
    at Array.filter (<anonymous>)
    at I (calc.ts:58)
    at o.finish (lasso-handler.ts:184)
    at o.onDocumentMouseUp (lasso-handler.ts:146)
t @ t-spatial.esm.js:522
(anonymous) @ calc.ts:6
I @ calc.ts:58
o.finish @ lasso-handler.ts:184
o.onDocumentMouseUp @ lasso-handler.ts:146

lasso-handler.ts:134 
mouseup event was missed

Thanks in advance.

**Comment by zakjan** [comment]
Hi, it seems that this library is going to be changed significantly in https://github.com/rowanwins/Leaflet.SvgShapeMarkers/issues/4 / https://github.com/rowanwins/Leaflet.SvgShapeMarkers/pull/5 so I'd better wait for this PR to be merged. There is a good chance that lasso is going to work as-is with the new version.

**Comment by gemmavnash** [comment]
Ok, thanks. :)

**Comment by zakjan** [comment]
I'm closing this issue for now if you don't mind. Let's wait for the above PR to be merged. Feel free to re-open if there is an issue with the new version.

**Comment by gemmavnash** [comment]
Ok. That’s fine.
I’ll be in touch.
Thanks.
Gemma

**Comment by jonoyuan** [comment]
Hey @zakjan, you'll have to capture `L.ShapeMarker`s in addition to `L.CircleMarker`s and `L.Marker`s. If I'm guessing right, once you do that there actually won't need to be any changes in [Leaflet.SvgShapeMarkers](https://github.com/rowanwins/Leaflet.SvgShapeMarkers).

**Comment by zakjan** [comment]
In your PR above https://github.com/rowanwins/Leaflet.SvgShapeMarkers/pull/12 you changed SvgShapeMarker to extend CircleMarker, that's great!

Lasso already supports CircleMarker, see https://github.com/zakjan/leaflet-lasso/blob/master/src/calc.ts#L30-L38 I suppose that everything should work without any change in Lasso, after your PR is merged and released?

**Comment by jonoyuan** [comment]
You'll have to repeat L30-36 but with `L.ShapeMarker`. I think.

In Leaflet.SvgShapeMarker it creates a new object type L.ShapeMarker. I don't think it replaces the original Circle marker (maybe it should?)
