### ISSUE TITLE
working with cluster

### ISSUE THREAD

**Issue by ipaidimarla** [zakjan/leaflet-lasso#30]
Hi,
I am not getting the correct selected layer count when using along with a cluster.

**Comment by zakjan** [comment]
Hi, thanks for reporting! Fixed the issue with selected markers. Released as 2.2.2.

However, I found another issue that enabling lasso causes clusters to change style from cluster to default marker. Not sure why is it happening. Maybe it got broken with recent Leaflet? I'm still investigating.

**Comment by coder-saroj** [comment]
Is this resolved. Because I am still getting same issue. Also can we change the free hand drawing to polygon draw which leaflet draw has.
Like the below link shows.

[https://gis.stackexchange.com/questions/296480/leaflet-popup-disappear-or-moved-over-drawn-polygon]([](https://gis.stackexchange.com/questions/296480/leaflet-popup-disappear-or-moved-over-drawn-polygon))

**Comment by zakjan** [comment]
Hi, it's not resolved yet. 

Regarding changing selection mode, I replied in your other issue #34

**Comment by Azbesciak** [comment]
Hello @zakjan , do you have any plans to fix this? I found your library, but unfortunately, I faced this issue. We are using [marker cluster](https://github.com/Leaflet/Leaflet.markercluster) and any try of selecting items results in...
```
TypeError: Cannot read property 'lat' of undefined
    at LatLngBounds.contains (LatLngBounds.js:178)
    at calc.ts:71
    at Array.filter (<anonymous>)
    at I (calc.ts:58)
    at o.finish (lasso-handler.ts:184)
    at o.onDocumentMouseMove (lasso-handler.ts:135)
    at ZoneDelegate.invokeTask (zone.js:429)
    at Object.onInvokeTask (ng_zone.ts:307)
    at ZoneDelegate.invokeTask (zone.js:428)
    at Zone.runTask (zone.js:200)
```

**Comment by zakjan** [comment]
@Azbesciak Hi, this seems as a different error. Could you investigate why it's undefined, and create a separate issue for it?

**Comment by zakjan** [comment]
I closed this issue for cleanup purposes, opened a new issue for the outstanding bug https://github.com/zakjan/leaflet-lasso/issues/41

**Comment by catbead** [comment]
Is this resolved? I am still getting the same issue. I listened to the lasso.finished and show the event.layers count, it is not the same when select with marker cluster

https://user-images.githubusercontent.com/112675155/203934633-46269185-e51b-4fad-8e97-8db2f8ad940e.mp4

**Comment by zakjan** [comment]
@catbead It seemed as resolved at that time, could you try to investigate where are the different counts coming from? What are your Leaflet, Leaflet.MaskerCluster and other plugins versions?
