### ISSUE TITLE
Clicking lasso button lead towards browser address bar with # sign.

### ISSUE THREAD

**Issue by Kaushik1987** [zakjan/leaflet-lasso#31]
Is there any way to remove # sign on click as it's creates issue with page with vertical scroll.

**Comment by zakjan** [comment]
Hi, what # sign do you mean? Could you share a screenshot? Thanks!

**Comment by Kaushik1987** [comment]
When u hover on lasso :
![hover](https://user-images.githubusercontent.com/11991900/99048939-3d73a300-25bc-11eb-8e2c-b7d4d0aa1e2f.png)

Once u click on lasso : 
![AfterClickpng](https://user-images.githubusercontent.com/11991900/99048934-3c427600-25bc-11eb-83fe-105e45de22ca.png)

I check the code & found that under **lasso-control.ts** , onAdd method you are adding  button.href = '#'. 
This is the one creating issue on click.

**Comment by zakjan** [comment]
Thanks for the screenshot and PR! Technically, `a` tag is invalid without `href` attribute. I have fixed it by replacing `#` with `javascript:void(0)`. Released as 2.2.3.
