### ISSUE TITLE
Workarounds to make leaflet-lasso work with touch devices (with Leaflet version 1.6.0 and above)

### ISSUE THREAD

**Issue by bucherc** [zakjan/leaflet-lasso#33]
Hello,

There is a closed issue:
https://github.com/zakjan/leaflet-lasso/issues/27

where you added support for touch devices by adding touch events to the map container (thank you!)

This works great with leaflet version 1.5.1 (your demo link uses this version of leaflet)

Unfortunately when you uptick the version of leaflet to anything above 1.5.1 the touch events no longer work on mobile / tablet touchscreen devices

Here is the change log for leaflet:
https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md

Would you be able to point me in the right direction to resolve this as we are using Leaflet 1.7.1 and can not go down to version 1.5.1.

Any help would be greatly appreciated.

Thanks,
-Chris Bucher

**Comment by zakjan** [comment]
Thanks @bucherc for the report! I found out that it's caused by Leaflet simulating touch events with mouse events. Since leaflet-lasso handles touch events explicitly, it seems safe to ignore these simulated events. Could you test just released 2.2.4?

**Comment by bucherc** [comment]
Hello!

You are fast! I just tested it and it works perfectly. The lasso control is
really amazing as it gets me an array of objects that I can sort through
for all layers. Much easier than drawing squares or polygons in my opinion.
Here is a screenshot of your lasso in what I'm creating.

Appreciate all your work with this!  Have a great day!

[image: lasso_shot.jpg]

Thanks,
Chris Bucher

**Comment by zakjan** [comment]
The screenshot didn't come through :)

**Comment by bucherc** [comment]
![lasso_shot](https://user-images.githubusercontent.com/11892881/107911890-4c972380-6f12-11eb-836b-057e030b87fe.jpg)

**Comment by zakjan** [comment]
Looks good! I worked on a similar water system map in past as well.
