### ISSUE TITLE
Can we change the selection mode to polygon selection

### ISSUE THREAD

**Issue by coder-saroj** [zakjan/leaflet-lasso#34]
Hi, I want to change the selection mode. As it is now a free hand draw selection which selects all polygons with in it, I want to change that to polygon like I can draw a polygon or a rectangle to select some layer. Is there any option for it.

**Comment by zakjan** [comment]
Hi, unfortunately no, this plugin is specialized for lasso selection. For other selection modes, you can explore other existing plugins at https://leafletjs.com/plugins.html#areaoverlay-selection
