### ISSUE TITLE
Left mouse button

### ISSUE THREAD

**Issue by Falke-Design** [zakjan/leaflet-lasso#8]
Thanks for uploading a new version! But why works the lasso only with the right mouse button and not with the left mouse button? That is very confusing in the first moment.

And while drawing with the right mouse button and then clicking with the left mouse button, the lasso polygon are not removed from the map.

**Comment by zakjan** [comment]
That's weird, it's supposed to be left button only. What OS/browser do you use?

**Comment by Falke-Design** [comment]
Firefox 67.0 on Win 10. But in Chrome it works.

**Comment by zakjan** [comment]
Partially it was a bug in the demo page (resetting selected layers after mouse button was released) and LassoHandler (allowing right click). It should be fixed in 2.0.2, only left mouse button is allowed now, please verify.
